import os, random
import numpy as np


def build_independence_mh_chain(
    action_file="action.npy",
    logp_file="logp.npy",
    samples_file="SPS.npy",
    output_chain="mh_chain.npy",
    output_accepted_samples="accepted_samples.npy",
    output_acceptance_rate="acceptance_rate.txt",
    output_logw="logw.npy",
    burn_in=0,
    seed=None,
    shuffle_proposals=False,
):
    """
    Construct an independence-Metropolis-Hastings chain from a pool of SPS proposal samples.

    Target distribution:
        pi(x) ∝ exp[-S(x)]

    Proposal distribution:
        q(x), with log q(x) provided by logp_file.

    MH acceptance probability:
        alpha(x_current -> x_proposal)
        = min(1, pi(x_proposal) q(x_current) / [pi(x_current) q(x_proposal)])

    In log form:
        log_alpha = [-S_new - logq_new] - [-S_cur - logq_cur]
                  = logw_new - logw_cur

    where:
        logw(x) = -S(x) - logq(x)

    Parameters
    ----------
    action_file : str
        Path to action.npy. This should contain S(x), i.e. negative log target
        up to an irrelevant additive constant.

    logp_file : str
        Path to logp.npy. This should contain log q(x), the proposal log-probability
        of each sample in DM.npy.

    samples_file : str
        Path to DM.npy. Proposal samples generated by the SPS / diffusion model.

    output_chain : str
        Output path for the full MH chain. Rejected proposals produce repeated states.

    output_accepted_samples : str
        Output path for accepted proposal samples only.
        WARNING: This is not the full MH ensemble because it does not contain rejected-state repetitions.

    output_acceptance_rate : str
        Output path for text diagnostics.

    output_logw : str
        Output path for logw = -S - logq.

    burn_in : int
        Number of initial chain states to discard before saving mh_chain.npy.

    seed : int or None
        Random seed.

    shuffle_proposals : bool
        If True, randomly permute the proposal pool before running MH.
        This can reduce accidental correlations in proposal ordering.

    Returns
    -------
    acceptance_rate : float
        MH proposal acceptance rate.

    chain : np.ndarray
        Saved MH chain after burn-in.

    accepted_samples : np.ndarray
        Samples corresponding to newly accepted proposals.
    """

    rng = np.random.default_rng(seed)

    print("Loading files...")
    S = np.load(action_file)
    logq = np.load(logp_file)
    samples = np.load(samples_file)

    N = min(len(S), len(logq), len(samples))

    if N < 2:
        raise ValueError("Need at least two samples to run MH.")

    S = np.asarray(S[:N], dtype=np.float64)
    logq = np.asarray(logq[:N], dtype=np.float64)
    samples = samples[:N]

    print(f"Action shape:  {S.shape}")
    print(f"logq shape:    {logq.shape}")
    print(f"Samples shape: {samples.shape}")
    print(f"Using N = {N} proposal samples")

    if shuffle_proposals:
        perm = rng.permutation(N)
        S = S[perm]
        logq = logq[perm]
        samples = samples[perm]
        print("Proposal pool shuffled.")

    # Importance log-weight:
    # logw = log pi(x) - log q(x) = -S(x) - logq(x), up to an additive constant.
    logw = -S - logq

    if not np.all(np.isfinite(logw)):
        bad = np.sum(~np.isfinite(logw))
        raise ValueError(f"logw contains {bad} non-finite values.")

    np.save(output_logw, logw)

    print("logw diagnostics:")
    print(f"  mean(logw) = {np.mean(logw):.8e}")
    print(f"  std(logw)  = {np.std(logw):.8e}")
    print(f"  min(logw)  = {np.min(logw):.8e}")
    print(f"  max(logw)  = {np.max(logw):.8e}")

    # Effective sample size diagnostic for raw reweighting.
    lw_shift = logw - np.max(logw)
    w = np.exp(lw_shift)
    ess = np.sum(w) ** 2 / np.sum(w ** 2)
    ess_ratio = ess / N

    print(f"  ESS/N      = {ess_ratio:.8e}")

    # Independence MH chain.
    #
    # cur stores the index of the current Markov-chain state in the proposal pool.
    # If a proposal is rejected, cur is unchanged and the old sample is appended again.
    cur = 0
    accepted = 0

    chain_indices = np.empty(N, dtype=np.int64)
    chain_indices[0] = cur

    # Store accepted proposal indices.
    # These are useful for diagnostics, but they are not the full MH ensemble.
    accepted_indices = []

    for i in range(1, N):
        log_alpha = logw[i] - logw[cur]

        # Accept with probability min(1, exp(log_alpha)).
#        if np.log(rng.random()) < min(0.0, log_alpha):
        if np.log(random.random()) < min(0.0, log_alpha):
            cur = i
            accepted += 1
            accepted_indices.append(i)

        # Important: always append the current state.
        # If rejected, this repeats the previous state.
        chain_indices[i] = cur

    acceptance_rate = accepted / (N - 1)

    if burn_in < 0:
        raise ValueError("burn_in must be non-negative.")

    if burn_in >= N:
        raise ValueError(f"burn_in={burn_in} is too large for chain length N={N}.")

    saved_indices = chain_indices[burn_in:]
    chain = samples[saved_indices]

    accepted_indices = np.asarray(accepted_indices, dtype=np.int64)
    accepted_samples = samples[accepted_indices]

    np.save(output_chain, chain)
    np.save(output_accepted_samples, accepted_samples)

    unique_visited = len(np.unique(chain_indices))
    repeated_fraction = 1.0 - unique_visited / N

    with open(output_acceptance_rate, "w") as f:
        f.write(f"Total proposals: {N - 1}\n")
        f.write(f"Accepted proposals: {accepted}\n")
        f.write(f"Acceptance rate: {acceptance_rate:.10f}\n")
        f.write(f"Raw chain length: {N}\n")
        f.write(f"Burn-in: {burn_in}\n")
        f.write(f"Saved chain length: {len(chain)}\n")
        f.write(f"Accepted samples length: {len(accepted_samples)}\n")
        f.write(f"Unique proposal states visited: {unique_visited}\n")
        f.write(f"Repeated-state fraction: {repeated_fraction:.10f}\n")
        f.write(f"ESS/N from raw importance weights: {ess_ratio:.10e}\n")
        f.write(f"mean(logw): {np.mean(logw):.10e}\n")
        f.write(f"std(logw): {np.std(logw):.10e}\n")
        f.write(f"min(logw): {np.min(logw):.10e}\n")
        f.write(f"max(logw): {np.max(logw):.10e}\n")

    print("\nMH diagnostics:")
    print(f"  Accepted proposals:     {accepted}/{N - 1}")
    print(f"  Acceptance rate:        {acceptance_rate:.8f}")
    print(f"  Raw chain length:       {N}")
    print(f"  Saved chain length:     {len(chain)}")
    print(f"  Accepted samples shape: {accepted_samples.shape}")
    print(f"  Unique states:          {unique_visited}")
    print(f"  Repeated fraction:      {repeated_fraction:.8f}")
    print(f"\nSaved chain to:           {output_chain}")
    print(f"Saved accepted samples to:{output_accepted_samples}")
    print(f"Saved diagnostics to:     {output_acceptance_rate}")
    print(f"Saved logw to:            {output_logw}")

    return acceptance_rate, chain, accepted_samples


def compute_observables(
    samples_file,
    output_file="observables.txt",
):
    """
    Compute |M|, susceptibility, and Binder cumulant from a sample chain.

    Assumes samples have shape:
        [N, Lx, Ly]
    or:
        [N, Lx, Ly, 1]

    Definitions:
        m = mean_x phi_x
        Magnetization = <|m|>
        Susceptibility = V * ( <m^2> - <|m|>^2 )
        Binder = 1 - <m^4> / (3 <m^2>^2)

    Note
    ----
    This function gives naive standard errors assuming independent samples.
    For a real MH chain, use blocking / jackknife for final quoted errors.
    """

    samples = np.load(samples_file)

    if samples.ndim == 4 and samples.shape[-1] == 1:
        samples = samples[..., 0]

    if samples.ndim != 3:
        raise ValueError(
            f"Expected samples with shape [N, Lx, Ly] or [N, Lx, Ly, 1], got {samples.shape}"
        )

    N, Lx, Ly = samples.shape
    V = Lx * Ly

    if N < 2:
        raise ValueError("Need at least two samples to compute errors.")

    m = np.mean(samples, axis=(1, 2))
    abs_m = np.abs(m)

    m2 = m ** 2
    m4 = m ** 4

    mag = np.mean(abs_m)
    chi = V * (np.mean(m2) - np.mean(abs_m) ** 2)
    binder = 1.0 - np.mean(m4) / (3.0 * np.mean(m2) ** 2)

    # Naive errors. Replace by blocking/jackknife for publication-quality results.
    mag_err = np.std(abs_m, ddof=1) / np.sqrt(N)

    chi_samples = V * (m2 - np.mean(abs_m) ** 2)
    chi_err = np.std(chi_samples, ddof=1) / np.sqrt(N)

    # For Binder, use jackknife because it is a nonlinear ratio.
    binder_jk = np.empty(N, dtype=np.float64)
    sum_m2 = np.sum(m2)
    sum_m4 = np.sum(m4)

    for i in range(N):
        mean_m2_jk = (sum_m2 - m2[i]) / (N - 1)
        mean_m4_jk = (sum_m4 - m4[i]) / (N - 1)
        binder_jk[i] = 1.0 - mean_m4_jk / (3.0 * mean_m2_jk ** 2)

    binder_jk_mean = np.mean(binder_jk)
    binder_err = np.sqrt((N - 1) * np.mean((binder_jk - binder_jk_mean) ** 2))

    with open(output_file, "w") as f:
        f.write(f"Samples: {N}\n")
        f.write(f"Lx: {Lx}\n")
        f.write(f"Ly: {Ly}\n")
        f.write(f"Volume: {V}\n")
        f.write(f"Magnetization <|m|>: {mag:.10f} +/- {mag_err:.10f}\n")
        f.write(f"Susceptibility:      {chi:.10f} +/- {chi_err:.10f}\n")
        f.write(f"Binder cumulant:     {binder:.10f} +/- {binder_err:.10f}\n")

    print("\nObservable results:")
    print(f"  Samples:          {N}")
    print(f"  Lattice:          {Lx} x {Ly}")
    print(f"  Magnetization:    {mag:.10f} ± {mag_err:.10f}")
    print(f"  Susceptibility:   {chi:.10f} ± {chi_err:.10f}")
    print(f"  Binder cumulant:  {binder:.10f} ± {binder_err:.10f}")
    print(f"\nSaved observables to: {output_file}")

    return {
        "N": N,
        "Lx": Lx,
        "Ly": Ly,
        "V": V,
        "magnetization": mag,
        "magnetization_error_naive": mag_err,
        "susceptibility": chi,
        "susceptibility_error_naive": chi_err,
        "binder": binder,
        "binder_error_jackknife": binder_err,
    }


def run_for_directory(
    data_dir,
    burn_in=0,
    seed=None,
    shuffle_proposals=False,
):
    """
    Convenience wrapper for one directory containing:
        action.npy
        logp.npy
        DM.npy
    """

    action_file = os.path.join(data_dir, "action.npy")
    logp_file = os.path.join(data_dir, "logp.npy")
    samples_file = os.path.join(data_dir, "DM.npy")

    output_chain = os.path.join(data_dir, "mh_chain.npy")
    output_accepted_samples = os.path.join(data_dir, "accepted_samples.npy")
    output_acceptance_rate = os.path.join(data_dir, "acceptance_rate.txt")
    output_logw = os.path.join(data_dir, "logw.npy")
    output_observables = os.path.join(data_dir, "mh_observables.txt")

    acc_rate, chain, accepted_samples = build_independence_mh_chain(
        action_file=action_file,
        logp_file=logp_file,
        samples_file=samples_file,
        output_chain=output_chain,
        output_accepted_samples=output_accepted_samples,
        output_acceptance_rate=output_acceptance_rate,
        output_logw=output_logw,
        burn_in=burn_in,
        seed=seed,
        shuffle_proposals=shuffle_proposals,
    )

    # Use the full MH chain for physical observables.
    # Do not use accepted_samples.npy for final MH observables because it does not include residence time.
    obs = compute_observables(
        samples_file=output_chain,
        output_file=output_observables,
    )

    return acc_rate, obs, accepted_samples


if __name__ == "__main__":
    # Modify these according to your actual generated folders.

    L_list = [64]

    # Use the actual kappa you want to analyze.
    Kappa = [0.27]

    burn_in = 0
    seed = 1234

    # If your DM.npy samples are independently generated by the diffusion model,
    # shuffle_proposals is optional. It can reduce ordering artifacts.
    shuffle_proposals = False

    for L in L_list:
        for kappa in Kappa:
            data_dir = f"kappa{kappa}L{L}"

            if not os.path.isdir(data_dir):
                print(f"\nSkipping missing directory: {data_dir}")
                continue

            print("\n" + "=" * 80)
            print(f"Running independence MH for: {data_dir}")
            print("=" * 80)

            acc_rate, obs, accepted_samples = run_for_directory(
                data_dir=data_dir,
                burn_in=burn_in,
                seed=seed,
                shuffle_proposals=shuffle_proposals,
            )

            np.save(data_dir+'/accepted_samples.npy', accepted_samples)
